# Generated by Django 4.2.7 on 2024-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_message_date_alter_message_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default='2020-05-01'),
        ),
    ]
