# Generated by Django 4.2.7 on 2024-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_message_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message_C',
        ),
    ]
