# Generated by Django 4.2.7 on 2024-02-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 14, 46, 16, 423675, tzinfo=datetime.timezone.utc)),
        ),
    ]
