# Generated by Django 4.2.7 on 2024-02-29 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 21, 21, 48, 893491, tzinfo=datetime.timezone.utc)),
        ),
    ]
